version: '3.1'
services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27018:27017
    networks:
      - webflux
    restart: always

  app:
    container_name: app
    build: ./
    environment:
      SERVER_PORT: 8080
      MONGO_DB_PORT: 27017
      MONGO_DB_HOST: mongo_db
      MONGO_DB: mongo_db
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 9082:8080
    networks:
      - webflux
    restart: always
    depends_on:
      - mongo_db
networks:
  webflux:
    driver: bridge